version: '3.8'
services:
  web:
    image: nginx
    volumes:
      - ./neuroelo_web:/usr/share/nginx/html:ro
    ports:
     - "8080:80"
       #environment:
       # - NGINX_HOST=foobar.com
       # - NGINX_PORT=80
